data:extend({

	--ID:418
	{
		type = "item",
		name = "y_crystal_dust",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/yb-dusts.png",
		group = "yuoki",
		subgroup = "y_line3",
		order = "f",
		stack_size = 200,
	},
	--ID:416
	{
		type = "item",
		name = "y_steinmehl",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/stone-dust.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		order = "f",
		stack_size = 250,
		weight = 2 * kg,
	},
	--ID:415
	{
		type = "item",
		name = "y_mixer_emu",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/water_mixer_icon.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_machinery",
		order = "u",
		stack_size = 25,
		place_result = "y_mixer_emu",
	},
	--ID:413
	{
		type = "item",
		name = "y_crystalizer",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/crys_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "u",
		stack_size = 25,
		place_result = "y_crystalizer",
	},
	--ID:412
	{
		type = "item",
		name = "y_hppump",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/hppump_icon.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_machinery",
		order = "v",
		stack_size = 25,
		place_result = "y_hppump",
	},
	--ID:410
	{
		type = "item",
		name = "y_trockner",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/base_factory_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "u",
		stack_size = 25,
		place_result = "y_trockner",
	},
	--ID:408
	{
		type = "item",
		name = "y_mox2fuelsplited",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox-c_splitted_icon.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "9",
		stack_size = 200,
		fuel_value = "600MJ",
		fuel_category = "chemical",
	},
	--ID:402
	{
		type = "item",
		name = "y_wood_wall",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/walls/wood_wall_icon.png",
		group = "yuoki",
		subgroup = "y_defense_walls",
		order = "1",
		stack_size = 150,
		fuel_value = "16MJ",
		fuel_category = "chemical",
		place_result = "y_wood_wall",
	},
	--ID:400
	{
		type = "item",
		name = "y_mox2fuel",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox2l.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "8",
		stack_size = 200,
		fuel_value = "7GJ",
		fuel_category = "yfusion",
	},
	--ID:399
	{
		type = "item",
		name = "y_mox2heated",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox2h.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "8",
		stack_size = 100,
	},
	--ID:398
	{
		type = "item",
		name = "y_mox2mixed",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox2p.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "8",
		stack_size = 100,
	},
	--ID:397
	{
		type = "item",
		name = "y_mox1fuel",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox1f.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "8",
		stack_size = 400,
		fuel_value = "1GJ",
		fuel_category = "yfusion",
	},
	--ID:396
	{
		type = "item",
		name = "y_mox1heated",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox1h.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "9",
		stack_size = 100,
	},
	--ID:395
	{
		type = "item",
		name = "y_mox1mixed",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mox1e.png",
		group = "yuoki-energy",
		subgroup = "y-fuel",
		order = "8",
		stack_size = 100,
	},
	--ID:394
	{
		type = "item",
		name = "y_moxmixer",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/fuel_mixer_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "9",
		stack_size = 25,
		place_result = "y_moxmixer",
	},
	--ID:392
	{
		type = "item",
		name = "yi_graphite",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/graphite_rod.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		order = "u",
		stack_size = 100,
	},
	--ID:359
	{
		type = "item",
		name = "y-conductive-coil-1",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/super-conductor.png",
		group = "yuoki",
		subgroup = "y_parts_e",
		order = "a",
		stack_size = 250,
	},
	--ID:358
	{
		type = "item",
		name = "y_signal_pole",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/signal_pole_icon.png",
		group = "yuoki-energy",
		subgroup = "y-electric",
		order = "h",
		stack_size = 100,
		place_result = "y_signal_pole",
	},
	--ID:356
	{
		type = "item",
		name = "y-orange-stuff",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/orange-stuff.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 800,
		weight = 1.25 * kg,
	},
	--ID:355
	{
		type = "item",
		name = "y-conductive-wire-1",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/wire_1.png",
		group = "yuoki",
		subgroup = "y_parts_e",
		order = "pe6",
		stack_size = 250,
	},
	--ID:354
	{
		type = "item",
		name = "y_structure_electric",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/caseing-n4wCable.png",
		group = "yuoki",
		subgroup = "y_parts_e",
		order = "p-g2a",
		stack_size = 150,
	},
	--ID:321
	{
		type = "item",
		name = "y_tile_slagbricks",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/path_tiles/bricks_3.png",
		group = "yuoki-energy",
		subgroup = "y_tiles",
		order = "c",
		stack_size = 500,
	},
	--ID:320
	{
		type = "item",
		name = "y_tile_slagpattern",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/path_tiles/muster_2.png",
		group = "yuoki-energy",
		subgroup = "y_tiles",
		order = "b",
		stack_size = 500,
	},
	--ID:319
	{
		type = "item",
		name = "y_tile_slagfilled",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/path_tiles/pslag_icon.png",
		group = "yuoki-energy",
		subgroup = "y_tiles",
		order = "a",
		stack_size = 500,
	},
	--ID:318
	{
		type = "item",
		name = "y_slag_brick",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/slag_brick.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		order = "l",
		stack_size = 400,
		weight = 2.5 * kg,
	},
	--ID:317
	{
		type = "item",
		name = "y_slag_granulate",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/dust_slag.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		order = "k",
		stack_size = 800,
		weight = 1.25 * kg,
	},
	--ID:316
	{
		type = "item",
		name = "y-pure-copper",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/pure-copper-n.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		order = "pc",
		stack_size = 250,
		weight = 2 * kg,
	},
	--ID:315
	{
		type = "item",
		name = "y-pure-iron",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/pure-iron-n.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		order = "pi",
		stack_size = 250,
		weight = 2 * kg,
	},
	--ID:314
	{
		type = "item",
		name = "y-richdust",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/richdust.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		order = "a",
		stack_size = 500,
		weight = 2 * kg,
	},
	--ID:313
	{
		type = "item",
		name = "y_block_heat",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/block_heat_icon.png",
		pictures = {
			layers = {
				{
					size = 64,
					filename = "__Yuoki__/graphics/entity/block_heat_icon.png",
					scale = 0.5,
					mipmap_count = 1,
				},
				{
					draw_as_light = true,
					size = 64,
					filename = "__Yuoki__/graphics/entity/block_heat_icon.png",
					scale = 0.5,
				},
			},
		},
		group = "yuoki",
		subgroup = "y-parts",
		order = "t",
		stack_size = 250,
		weight = 4 * kg,
		auto_recycle = false,
	},
	--ID:312
	{
		type = "item",
		name = "y_block_cold",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/block_cold_icon.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "s",
		stack_size = 250,
		weight = 4 * kg,
		auto_recycle = false,
	},
	--ID:311
	{
		type = "item",
		name = "y_smelter",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/smelter_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "t",
		stack_size = 25,
		place_result = "y_smelter",
		weight = 1000 * kg,
	},
	--ID:310
	{
		type = "item",
		name = "y_charger",
		icon_size = 64,
		icon = "__Yuoki__/graphics/entity/charger_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "a",
		stack_size = 25,
		place_result = "y_charger",
	},
	--ID:306
	{
		type = "item",
		name = "y_greensign",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/sign_green_icon.png",
		group = "yuoki",
		subgroup = "y-stargate-r",
		order = "a",
		stack_size = 100000,
		auto_recycle = false,
	},
	--ID:305
	{
		type = "item",
		name = "ypfw_trader_sign",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/sign_trader_icon.png",
		group = "yuoki",
		subgroup = "y-stargate-r",
		order = "a",
		stack_size = 100000,
		auto_recycle = false,
	},
	--ID:290
	{
		type = "item",
		name = "y_rwtechsign",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/sign_tech_icon.png",
		group = "yuoki",
		subgroup = "y-stargate-r",
		order = "a",
		stack_size = 100000,
		auto_recycle = true,
	},
	--ID:289
	{
		type = "item",
		name = "y-chip-2",
		icon_size = 96,
		icon = "__Yuoki__/graphics/icons/chip2-icon.png",
		group = "yuoki",
		subgroup = "y_parts_e",
		order = "ac-2",
		stack_size = 250,
		weight = 2 * kg,
	},
	--ID:288
	{
		type = "item",
		name = "y-chip-1",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/chip1-icon.png",
		group = "yuoki",
		subgroup = "y_parts_e",
		order = "ac-1",
		stack_size = 250,
	},
	--ID:287
	{
		type = "item",
		name = "y-basic-t2-mf",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/maschine-frame-t2.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g5",
		stack_size = 50,
	},
	--ID:286
	{
		type = "item",
		name = "y-basic-t1-mf",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/maschine-frame-t1.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g4",
		stack_size = 50,
	},
	--ID:278
	{
		type = "item",
		name = "yi_magnetron",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/magnetron.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "a",
		stack_size = 100,
	},
	--ID:277
	{
		type = "item",
		name = "yi_roboport",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/roboport_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "1",
		stack_size = 25,
		place_result = "yi_roboport",
	},
	-- the 8080 - JATMN
	{
		type = "item",
		name = "j_yi_roboport1",
		icon_size = 64,
		icons = {
			{
				icon = "__Yuoki__/graphics/icons/8080_icon.png",
				tint = { r = 179 / 255, g = 198 / 255, b = 255 / 255 },
				scale = 0.5,
			},
		},
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "2",
		stack_size = 25,
		place_result = "j_yi_roboport1",
	},
	--ID:276
	{
		type = "item",
		name = "yi_beacon",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/beacon_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "a",
		stack_size = 25,
		place_result = "yi_beacon",
	},
	--ID:275
	{
		type = "item",
		name = "yi_radar",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/radar_icon.png",
		group = "yuoki",
		subgroup = "y_line1b",
		order = "a",
		stack_size = 25,
		place_result = "yi_radar",
	},
	--ID:261
	{
		type = "item",
		name = "yi_logistic-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rob_log_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "a",
		stack_size = 100,
		place_result = "yi_logistic-robot",
	},
	-- Logistic bot 2 - (JATMN)
	{
		type = "item",
		name = "j_logistic2-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/j_logistic2-robot_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "a2",
		stack_size = 50,
		place_result = "j_logistic2-robot",
		weight = 20 * kg,
	},
	--ID:260
	{
		type = "item",
		name = "yi_construction-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rob_con_icon.png",
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "d",
		stack_size = 100,
		place_result = "yi_construction-robot",
	},
	-- Construction bot 2 - (JATMN)
	{
		type = "item",
		name = "j_construction2-robot",
		icon_size = 64,
		icons = {
			{
				icon = "__Yuoki__/graphics/icons/rob_con_icon.png",
				tint = { r = 224 / 255, g = 158 / 255, b = 158 / 255 },
			},
		},
		group = "yuoki",
		subgroup = "j-y-logi-9",
		order = "d2",
		stack_size = 50,
		place_result = "j_construction2-robot",
		weight = 20 * kg,
	},
	--ID:238
	{
		type = "item",
		name = "y_gauge",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/gauge.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_parts",
		order = "a",
		stack_size = 100,
	},
	--ID:237
	{
		type = "item",
		name = "y_flowcheck_10",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/flow_indicator_icon.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_parts",
		order = "a",
		stack_size = 30,
		place_result = "y_flowcheck_10",
	},
	--ID:224
	{
		type = "item",
		name = "ye_science_blue",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/sign_science_icon.png",
		group = "yuoki",
		subgroup = "y-stargate-r",
		order = "a",
		stack_size = 100000,
		auto_recycle = false,
	},
	--ID:208
	{
		type = "item",
		name = "y-crystal2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/crystal_2.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 800,
		weight = 1.25 * kg,
	},
	--ID:207
	{
		type = "item",
		name = "y_quantrinum_infused",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/charged_quantrinum_icon.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 25,
	},
	--ID:206
	{
		type = "item",
		name = "y_crystal2_combined",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/blue_style.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 250,
		weight = 4 * kg,
	},
	--ID:177
	{
		type = "item",
		name = "y_usedcatalyst",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/icon_spcat32.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_material",
		order = "ca",
		stack_size = 300,
	},
	--ID:176
	{
		type = "item",
		name = "y_catalyst_base",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/icon_catalyst_base.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_material",
		order = "b1",
		stack_size = 450,
	},
	--ID:174
	{
		type = "item",
		name = "y-bluegear",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/bluegear-icon.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g1",
		stack_size = 150,
	},
	--ID:173
	{
		type = "item",
		name = "y-dirt",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/dirt_32.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		order = "a",
		stack_size = 5000,
	},
	--ID:172
	{
		type = "item",
		name = "y_organic_dust",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/sawdust_32.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_material",
		order = "a1",
		stack_size = 700,
	},
	--ID:171
	{
		type = "item",
		name = "y-raw-fuelnium",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/crystal_energy.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 500,
		weight = 2 * kg,
	},
	--ID:170
	{
		type = "item",
		name = "y_catalyst_ft",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/icon_ftcat32.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_material",
		order = "cc",
		stack_size = 320,
	},
	--ID:169
	{
		type = "item",
		name = "y_catalyst_bp",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/icon_bpcat28.png",
		group = "yuoki_liquids",
		subgroup = "y_refine_material",
		order = "cb",
		stack_size = 280,
	},
	--ID:168

	--ID:167
	{
		type = "item",
		name = "y_structure_element",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/structur_element.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g2",
		stack_size = 150,
	},
	--ID:166
	{
		type = "item",
		name = "y-heat-pipe",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/heat-pipe.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g6",
		stack_size = 150,
	},
	--ID:165
	{
		type = "item",
		name = "y-crystal-cnd",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/crystal_3.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 500,
		weight = 20 * kg,
	},
	--ID:164
	{
		type = "item",
		name = "y-coal-dust",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/coal-dust.png",
		group = "yuoki",
		subgroup = "y-fuel",
		order = "a",
		stack_size = 100,
		fuel_value = "3MJ",
		fuel_category = "chemical",
	},
	--ID:162
	{
		type = "item",
		name = "y-fame",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/fame-icon.png",
		group = "yuoki",
		subgroup = "y-stargate-f",
		order = "a",
		stack_size = 100,
		auto_recycle = false,
	},
	--ID:158
	{
		type = "item",
		name = "y_structure_vessel",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/vessel_structure_icon.png",
		group = "yuoki",
		subgroup = "y-parts",
		order = "p-g3",
		stack_size = 100,
	},
	--ID:138
	{
		type = "item",
		name = "y-quantrinum",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/quantrinum.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "w-quantrinum",
		stack_size = 25,
		weight = 40 * kg,
	},
	--ID:137
	{
		type = "item",
		name = "y-unicomp-a2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/uni-komp-a2-icon.png",
		group = "yuoki",
		subgroup = "y-raw-material",
		order = "a",
		stack_size = 500,
		auto_recycle = false,
		weight = 2 * kg,
	},
	--ID:136
	{
		type = "item",
		name = "y-infused-uca2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/infused_uca2.png",
		group = "yuoki",
		subgroup = "y-fuel",
		order = "a",
		stack_size = 50,
		fuel_value = "3GJ",
		fuel_category = "chemical",
	},
})
