data:extend({
	{
		type = "item",
		name = "y-coal-brikett",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/coal_brikett.png",
		group = "yuoki",
		subgroup = "y-fuel",
		fuel_category = "chemical",
		fuel_value = "18MJ",
		stack_size = 830,
	},
	{
		type = "item",
		name = "y-coal-stack",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/coal_briketts.png",
		group = "yuoki",
		subgroup = "y-fuel",
		fuel_category = "chemical",
		fuel_value = "57MJ",
		stack_size = 350,
	},
	{
		type = "item",
		name = "y-mixed-fuel",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mix-fuel.png",
		group = "yuoki",
		subgroup = "y-fuel",
		--fuel_category = {"chemical"}, fuel_value = "25MJ",
		stack_size = 400,
	},
	{
		type = "item",
		name = "y-mixed-fuel-loaded",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/mix-fuel-loaded.png",
		group = "yuoki",
		subgroup = "y-fuel",
		fuel_category = "chemical",
		fuel_value = "40MJ",
		stack_size = 250,
	},
	{
		type = "item",
		name = "y-wooden-brikett",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/wood_brikett_32.png",
		group = "yuoki",
		subgroup = "y-fuel",
		fuel_category = "chemical",
		fuel_value = "10MJ",
		stack_size = 250,
	},
	{
		type = "item",
		name = "y-wooden-brikett-packed",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/wood-pellets.png",
		group = "yuoki",
		subgroup = "y-fuel",
		fuel_category = "chemical",
		fuel_value = "40MJ",
		stack_size = 250,
	},

	{
		type = "item",
		name = "y-crystal2",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/crystal_2.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		stack_size = 700,
	},
	{
		type = "item",
		name = "y-c_mud",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/c_mud_icon.png",
		group = "yuoki",
		subgroup = "yuoki-archaeology",
		stack_size = 500,
		weight = 2 * kg,
	},

	{
		type = "item",
		name = "y-dry_mud",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/dry_mud_icon.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		--fuel_category = {"chemical"},
		--fuel_value = "10MJ",
		stack_size = 500,
		weight = 2 * kg,
	},

	{
		type = "item",
		name = "y-toxic-dust",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/toxic-dust_icon.png",
		group = "yuoki",
		subgroup = "yuoki-formpress",
		stack_size = 1000,
		weight = 1 * kg,
	},
})
