data:extend(
{
	-- pure atomic constructs
	{
		type = "recipe",
		name = "y-ac-uc2b1-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "bauxite-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b2-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "cobalt-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},		
	{
		type = "recipe",
		name = "y-ac-uc2b3-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "gem-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b4-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "gold-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2b5-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "lead-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2b6-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "nickel-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b7-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "quartz",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b8-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "rutile-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2b9-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "silver-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b10-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "sulfur",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b11-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "tin-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2b12-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "tungsten-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2b13-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "zinc-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	

	-- reverts
	{
		type = "recipe",
		name = "y-ac-uc2r1-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"bauxite-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r2-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"cobalt-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	
	{
		type = "recipe",
		name = "y-ac-uc2r3-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"gem-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-ucrb4-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"gold-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2r5-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"lead-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2r6-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"nickel-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r7-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"quartz", 20},}, 
		result = "quartz",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2r8-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"rutile-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2r9-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"silver-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r10-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"sulfur", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2r11-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"tungsten-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2r12-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"tungsten-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	{
		type = "recipe",
		name = "y-ac-uc2r13-recipe", order="a",
		energy_required = 2.0,
		enabled = "true",
		ingredients = {{"zinc-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	
	
	
})	