data:extend({
	-- pure atomic constructs
	{
		type = "recipe",
		name = "y-ac-uc2b1",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = {
			{ type = "item", name = "bauxite-ore", amount = 20 },
		},
		--result = "bauxite-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b2-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "cobalt-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},		
	{
		type = "recipe",
		name = "y-ac-uc2b3-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "gem-ore",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b4",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "gold-ore", amount = 20 } },
		--result = "gold-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2b5",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "lead-ore", amount = 20 } },
		--result = "lead-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2b6",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "nickel-ore", amount = 20 } },
		--result = "nickel-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b7-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "quartz",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b8",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "rutile-ore", amount = 20 } },
		--result = "rutile-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2b9",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "silver-ore", amount = 20 } },
		--result = "silver-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2b10-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"y-unicomp-a2", 1},}, 
		result = "sulfur",
		result_count = 20,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2b11",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "tin-ore", amount = 20 } },
		--result = "tin-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2b12",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "tungsten-ore", amount = 20 } },
		--result = "tungsten-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2b13",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "y-unicomp-a2", amount = 1 } },
		results = { { type = "item", name = "zinc-ore", amount = 20 } },
		--result = "zinc-ore",
		--result_count = 20,
		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_green.png",
	},

	-- reverts
	{
		type = "recipe",
		name = "y-ac-uc2r1",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "bauxite-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r2-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"cobalt-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	
	{
		type = "recipe",
		name = "y-ac-uc2r3-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"gem-ore", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-ucrb4",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "gold-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2r5",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "lead-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2r6",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { "nickel-ore", 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r7-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"quartz", 20},}, 
		result = "quartz",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2r8",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "rutile-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2r9",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "silver-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	--[[
	{
		type = "recipe",
		name = "y-ac-uc2r10-recipe", order="a",
		energy_required = 2.0,
		enabled = true,
		ingredients = {{"sulfur", 20},}, 
		result = "y-unicomp-a2",
		result_count = 1,
		subgroup = "y-atomics", 
		category = "yuoki-atomics-recipe",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},	
	]]
	{
		type = "recipe",
		name = "y-ac-uc2r11",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "tungsten-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2r12",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "tungsten-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
	{
		type = "recipe",
		name = "y-ac-uc2r13",
		order = "a",
		energy_required = 2.0,
		enabled = true,
		ingredients = { { type = "item", name = "zinc-ore", amount = 20 } },
		results = { { type = "item", name = "y-unicomp-a2", amount = 1 } },

		subgroup = "y-atomics",
		category = "yuoki-atomics",
		icon = "__Yuoki__/graphics/icons/crystal_1.png",
	},
})
