local robot_animations = {}
robot_animations.logistic_robot = {
	shadow_idle = {
		filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 115,
		height = 57,
		shift = util.by_pixel(31.75, 19.75),
		direction_count = 16,
		y = 57,
		scale = 0.5,
		draw_as_shadow = true,
	},
	shadow_idle_with_cargo = {
		filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 115,
		height = 57,
		shift = util.by_pixel(31.75, 19.75),
		direction_count = 16,
		scale = 0.5,
		draw_as_shadow = true,
	},
	shadow_in_motion = {
		filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 115,
		height = 57,
		shift = util.by_pixel(31.75, 19.75),
		direction_count = 16,
		y = 57 * 3,
		scale = 0.5,
		draw_as_shadow = true,
	},
	shadow_in_motion_with_cargo = {
		filename = "__base__/graphics/entity/logistic-robot/logistic-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 115,
		height = 57,
		shift = util.by_pixel(31.75, 19.75),
		direction_count = 16,
		y = 114,
		scale = 0.5,
		draw_as_shadow = true,
	},
}

robot_animations.construction_robot = {
	shadow_idle = {
		filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 104,
		height = 49,
		shift = util.by_pixel(33.5, 18.75),
		direction_count = 16,
		scale = 0.5,
		draw_as_shadow = true,
	},
	shadow_in_motion = {
		filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 104,
		height = 49,
		shift = util.by_pixel(33.5, 18.75),
		direction_count = 16,
		scale = 0.5,
		draw_as_shadow = true,
	},
	working = {
		filename = "__base__/graphics/entity/construction-robot/construction-robot-working.png",
		priority = "high",
		line_length = 2,
		width = 57,
		height = 74,
		frame_count = 2,
		shift = util.by_pixel(-0.25, -5),
		direction_count = 16,
		animation_speed = 0.3,
		scale = 0.5,
	},
	shadow_working = {
		filename = "__base__/graphics/entity/construction-robot/construction-robot-shadow.png",
		priority = "high",
		line_length = 16,
		width = 104,
		height = 49,
		repeat_count = 2,
		shift = util.by_pixel(33.5, 18.75),
		direction_count = 16,
		scale = 0.5,
		draw_as_shadow = true,
	},
}

robot_animations.sparks = {
	{
		filename = "__base__/graphics/entity/sparks/sparks-01.png",
		draw_as_glow = true,
		width = 39,
		height = 34,
		frame_count = 19,
		line_length = 19,
		shift = { -0.109375, 0.3125 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
	{
		filename = "__base__/graphics/entity/sparks/sparks-02.png",
		draw_as_glow = true,
		width = 36,
		height = 32,
		frame_count = 19,
		line_length = 19,
		shift = { 0.03125, 0.125 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
	{
		filename = "__base__/graphics/entity/sparks/sparks-03.png",
		draw_as_glow = true,
		width = 42,
		height = 29,
		frame_count = 19,
		line_length = 19,
		shift = { -0.0625, 0.203125 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
	{
		filename = "__base__/graphics/entity/sparks/sparks-04.png",
		draw_as_glow = true,
		width = 40,
		height = 35,
		frame_count = 19,
		line_length = 19,
		shift = { -0.0625, 0.234375 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
	{
		filename = "__base__/graphics/entity/sparks/sparks-05.png",
		draw_as_glow = true,
		width = 39,
		height = 29,
		frame_count = 19,
		line_length = 19,
		shift = { -0.109375, 0.171875 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
	{
		filename = "__base__/graphics/entity/sparks/sparks-06.png",
		draw_as_glow = true,
		width = 44,
		height = 36,
		frame_count = 19,
		line_length = 19,
		shift = { 0.03125, 0.3125 },
		tint = { 1.0, 0.9, 0.0, 1.0 },
		animation_speed = 0.3,
	},
}

data:extend({

	{
		type = "logistic-robot",
		name = "yi_logistic-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rob_log_icon.png",
		flags = { "placeable-player", "player-creation", "placeable-off-grid", "not-on-map" },
		minable = { hardness = 0.1, mining_time = 0.1, result = "yi_logistic-robot" },
		max_health = 800,
		resistances = {
			{ type = "physical", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 5, percent = 50 },
			{ type = "acid", decrease = 5, percent = 50 },
		},
		collision_box = { { 0, 0 }, { 0, 0 } },
		selection_box = { { -0.5, -1.5 }, { 0.5, -0.5 } },
		max_payload_size = 3,
		speed = 0.20,
		transfer_distance = 0.5,
		max_energy = "2.5MJ",
		energy_per_tick = "0.025kJ",
		speed_multiplier_when_out_of_energy = 0.2,
		energy_per_move = "2.5kJ",
		min_to_charge = 0.2,
		max_to_charge = 0.9,
		idle = {
			filename = "__Yuoki__/graphics/entity/rob_log_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		idle_with_cargo = {
			filename = "__Yuoki__/graphics/entity/rob_log_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion = {
			filename = "__Yuoki__/graphics/entity/rob_log_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion_with_cargo = {
			filename = "__Yuoki__/graphics/entity/rob_log_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		shadow_idle = robot_animations.logistic_robot.shadow_idle,
		shadow_idle_with_cargo = robot_animations.logistic_robot.shadow_idle_with_cargo,
		shadow_in_motion = robot_animations.logistic_robot.shadow_in_motion,
		shadow_in_motion_with_cargo = robot_animations.logistic_robot.shadow_in_motion_with_cargo,
		--working_sound = flying_robot_sounds(),
		cargo_centered = { 0.0, 0.2 },
	},

	{
		type = "logistic-robot",
		name = "j_logistic2-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/j_logistic2-robot_icon.png",
		flags = { "placeable-player", "player-creation", "placeable-off-grid", "not-on-map" },
		minable = { hardness = 0.1, mining_time = 0.1, result = "j_logistic2-robot" },
		max_health = 1200,
		resistances = {
			{ type = "physical", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 5, percent = 50 },
			{ type = "acid", decrease = 5, percent = 50 },
		},
		collision_box = { { 0, 0 }, { 0, 0 } },
		selection_box = { { -0.5, -1.5 }, { 0.5, -0.5 } },
		max_payload_size = 6,
		speed = 0.30,
		transfer_distance = 0.74,
		max_energy = "3.75MJ",
		energy_per_tick = "0.037kJ",
		speed_multiplier_when_out_of_energy = 0.2,
		energy_per_move = "3.75kJ",
		min_to_charge = 0.2,
		max_to_charge = 0.9,
		idle = {
			filename = "__Yuoki__/graphics/entity/j_logistic2-robot.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		idle_with_cargo = {
			filename = "__Yuoki__/graphics/entity/j_logistic2-robot.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion = {
			filename = "__Yuoki__/graphics/entity/j_logistic2-robot.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion_with_cargo = {
			filename = "__Yuoki__/graphics/entity/j_logistic2-robot.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		shadow_idle = robot_animations.logistic_robot.shadow_idle,
		shadow_idle_with_cargo = robot_animations.logistic_robot.shadow_idle_with_cargo,
		shadow_in_motion = robot_animations.logistic_robot.shadow_in_motion,
		shadow_in_motion_with_cargo = robot_animations.logistic_robot.shadow_in_motion_with_cargo,
		--working_sound = flying_robot_sounds(),
		cargo_centered = { 0.0, 0.2 },
	},

	{
		type = "construction-robot",
		name = "yi_construction-robot",
		icon_size = 64,
		icon = "__Yuoki__/graphics/icons/rob_con_icon.png",
		flags = { "placeable-player", "player-creation", "placeable-off-grid", "not-on-map" },
		minable = { hardness = 0.1, mining_time = 0.1, result = "yi_construction-robot" },
		max_health = 800,
		resistances = {
			{ type = "physical", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 5, percent = 50 },
			{ type = "acid", decrease = 5, percent = 50 },
		},
		collision_box = { { 0, 0 }, { 0, 0 } },
		selection_box = { { -0.5, -1.5 }, { 0.5, -0.5 } },
		max_payload_size = 3,
		speed = 0.20,
		transfer_distance = 0.5,
		max_energy = "2.5MJ",
		energy_per_tick = "0.025kJ",
		speed_multiplier_when_out_of_energy = 0.2,
		energy_per_move = "2.5kJ",
		min_to_charge = 0.2,
		max_to_charge = 0.9,
		working_light = { intensity = 0.8, size = 3 },
		idle = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		working = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
			animation_speed = 0.3,
			scale = 0.5,
		},
		smoke = {
			filename = "__base__/graphics/entity/smoke-construction/smoke-01.png",
			width = 39,
			height = 32,
			frame_count = 19,
			line_length = 19,
			shift = { 0.078125, -0.15625 },
			animation_speed = 0.3,
		},
		sparks = robot_animations.sparks,
		shadow_idle = robot_animations.construction_robot.shadow_idle,
		shadow_idle_with_cargo = robot_animations.construction_robot.shadow_idle_with_cargo,
		shadow_in_motion = robot_animations.construction_robot.shadow_in_motion,
		shadow_in_motion_with_cargo = robot_animations.construction_robot.shadow_in_motion_with_cargo,
		shadow_working = robot_animations.construction_robot.shadow_in_motion,
		--repair_pack = "repair-pack",
		--working_sound = flying_robot_sounds(),
		--cargo_centered = {0.0, 0.2},
		construction_vector = { 0.30, 0.22 },
		icon_draw_specification = { shift = { 0, -0.2 }, scale = 0.5, render_layer = "air-entity-info-icon" },
	},

	{
		type = "construction-robot",
		name = "j_construction2-robot",
		icon_size = 64,
		icons = {
			{
				icon = "__Yuoki__/graphics/icons/rob_con_icon.png",
				tint = { r = 224 / 255, g = 158 / 255, b = 158 / 255 },
			},
		},
		flags = { "placeable-player", "player-creation", "placeable-off-grid", "not-on-map" },
		minable = { hardness = 0.1, mining_time = 0.1, result = "j_construction2-robot" },
		max_health = 800,
		resistances = {
			{ type = "physical", decrease = 5, percent = 50 },
			{ type = "impact", decrease = 5, percent = 50 },
			{ type = "acid", decrease = 5, percent = 50 },
		},
		collision_box = { { 0, 0 }, { 0, 0 } },
		selection_box = { { -0.5, -1.5 }, { 0.5, -0.5 } },
		max_payload_size = 6,
		speed = 0.30,
		transfer_distance = 0.74,
		max_energy = "3.75MJ",
		energy_per_tick = "0.037kJ",
		speed_multiplier_when_out_of_energy = 0.2,
		energy_per_move = "3.75kJ",
		min_to_charge = 0.2,
		max_to_charge = 0.9,
		working_light = { intensity = 0.8, size = 3 },
		idle = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			tint = { r = 224 / 255, g = 158 / 255, b = 158 / 255 },
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
		},
		in_motion = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			tint = { r = 224 / 255, g = 158 / 255, b = 158 / 255 },
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
			--y = 36
		},
		working = {
			filename = "__Yuoki__/graphics/entity/rob_con_sheet.png",
			tint = { r = 224 / 255, g = 158 / 255, b = 158 / 255 },
			priority = "high",
			line_length = 16,
			width = 40,
			height = 40,
			frame_count = 1,
			shift = { 0, 0 },
			direction_count = 16,
			animation_speed = 0.3,
			scale = 0.5,
		},
		smoke = {
			filename = "__base__/graphics/entity/smoke-construction/smoke-01.png",
			width = 39,
			height = 32,
			frame_count = 19,
			line_length = 19,
			shift = { 0.078125, -0.15625 },
			animation_speed = 0.3,
		},
		sparks = robot_animations.sparks,
		shadow_idle = robot_animations.construction_robot.shadow_idle,
		shadow_idle_with_cargo = robot_animations.construction_robot.shadow_idle_with_cargo,
		shadow_in_motion = robot_animations.construction_robot.shadow_in_motion,
		shadow_in_motion_with_cargo = robot_animations.construction_robot.shadow_in_motion_with_cargo,
		shadow_working = robot_animations.construction_robot.shadow_in_motion,
		--repair_pack = "repair-pack",
		--working_sound = flying_robot_sounds(),
		cargo_centered = { 0.0, 0.2 },
		construction_vector = { 0.30, 0.22 },
	},
})
